# Generated by Django 3.0.10 on 2020-10-09 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='test',
        ),
    ]
