# Generated by Django 3.0.10 on 2020-10-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0005_auto_20201009_1141'),
        ('crawling', '0002_auto_20201009_1124'),
    ]

    operations = [
    ]
