# Generated by Django 3.0.10 on 2020-10-09 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0006_merge_20201009_1259'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='test',
        ),
    ]
