# Generated by Django 3.0.10 on 2020-10-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0007_auto_20201009_1313'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='crawling_post',
        ),
    ]
