# Generated by Django 3.0.10 on 2020-10-09 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0008_auto_20201009_1333'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='test',
        ),
    ]
