# Generated by Django 3.0.10 on 2020-10-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0009_auto_20201009_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('day', models.TextField()),
            ],
            options={
                'db_table': 'testdb',
                'managed': False,
            },
        ),
    ]
